### ISSUE TITLE
texttable should be marked as Python 3 capable

### ISSUE THREAD

**Issue by foutaise** [chhantyal/py3readiness#58] opened 2018-11-16 14:43 UTC
Hi, [texttable](https://github.com/foutaise/texttable) author here.

A user informed me that texttable is reported as python3 incompatible on your site. Please mark it as  compatible. Even the caniusepython3 library is ok:
```
$ python -c "import caniusepython3; print(caniusepython3.check(projects=['texttable']))"
True
```

https://caniusepython3.com/project/texttable

Best regards,

**Comment by hugovk** [comment] 2018-11-16 15:22
Hi, the problem is the data has been updated in a while.

https://github.com/chhantyal/py3readiness/pull/59 is an update. Texttable drops out of the top 360, but when https://github.com/chhantyal/py3readiness/pull/57 is merged it'll probably be back again, and green.

Thanks!

**Closed** 2018-11-16 15:45 UTC
